substitutions:
  _REGION: europe-north1
  _REPO: budgetapp

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform=linux/amd64
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/budgetapp
      - .

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/budgetapp
